config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

 authenticate :admin_user do
    get '/' => redirect('/doc/index.html?url=/apidocs/api-docs.json')
  end
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: :json }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

    resources :managers do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :hotels do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :customers do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :reviews do
      
    end
  
    resources :reservations do
      member do
        get 'cancel'
        post 'details'
        post 'approve'
      end
    end

  end
end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  enum status: [:pending, :confirmed, :hotel_cancelled, :user_cancelled]

  belongs_to :hotel
  belongs_to :customer

  has_many :reservation_details

  after_update :change_status if :allowed_change?

  def approve (table_ids)
    self.update(:status => :confirmed)

    arr = table_ids.split(',')
    details = []
    arr.each do | id |
      detail = { table_id: id }
      details.push( detail)
    end

    self.reservation_details.create( details)
    Table.where(id: arr).update_all(:status => true)
  end


  def self.details(params)
  	binding.pry
  	details = self.where("hotel_id = ? AND from <= ? AND to >= ?", params[:hotel_id], params[:from], params[:to])
  end

  private

  def change_status
    ids = self.reservation_details.pluck(:table_id)

    Table.where(id: ids).update_all(:status => false)
  end

  def allowed_change?
    self.status_changed?(from: [:pending , :confirmed] , to: [:hotel_cancelled, :user_cancelled])
  end
end

app/controllers/api/v1/reservations_controller.rb
class Api::V1::ReservationsController < Api::V1::ApiController

  swagger_controller :reservations, " Reservations Controller"


  swagger_api :index do
    summary 'Lists all the reservations'
  end
  def index
    @reservations = Reservation.all
    render json: { meta: meta_response( 200 , 'all ok'), reservations: @reservations }
  end


  swagger_api :show do
    summary 'Show details of a reservation'

    param :path, :id, :integer, :required, "ID"
  end

  def show
    begin
      @reservation = Reservation.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), reservation: @reservation}
      return
    end

    render json: { meta: meta_response( 200, 'all ok'), review: @reservation }
  end



  def new
    @reservation = Reservation.new
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end


  swagger_api :create do
    summary 'Create a new reservation'

    param :form, :customer_id, :integer, :required, "Customer ID"
    param :form, :hotel_id, :integer, :required, "Hotel ID"
    param :form, :no_of_persons, :integer, :required, "No of Persons"
    param :form, :from, :date, :required, "From"
    param :form, :to, :date, :required, "to"
    param :form, :comment, :string, :optional, "Comment"
  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      render json: { meta: meta_response( 200, 'all ok'), reservation: @reservation}
    else
      render json: { meta: meta_response( 500, 'Server Error'), reservation: @reservation}
    end
  end


  swagger_api :approve do
    summary 'Approves a reservation'

    param :path, :id, :integer, :required, "Reservation ID"
    param :form, :table_id, :string, :required, "Table ID"
  end

  def approve
    begin
      @reservation = Reservation.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), reservation: @reservation}
      return
    end

    if @reservation.approve( params[:table_id])
      render json: { meta: meta_response( 200, 'ok'), reservation: @reservation }
    else
      render json: { meta: meta_response( 500, 'Server Error'), reservation: @reservation}
    end
  end


  swagger_api :update do
    summary 'Update an existing reservation'

    param :path, :id, :integer, :required, "ID"
    param :form, :no_of_persons, :integer, :optional, "No Of Persons"
    param :form, :from, :date, :optional, "From"
    param :form, :to, :date, :optional, "To"
    param :form, :comment, :string, :optional, "Comment"
  end

  def update
    begin
      @reservation = Reservation.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), reservation: @reservation}
      return
    end

    if @reservation.update(reservation_params)
      render json: { meta: meta_response( 200, 'all ok'), reservation: @reservation}
    else
      render json: { meta: meta_response( 500, 'Server error'), reservation: @reservation}
    end
  end


  swagger_api :cancel do
    summary 'Cancel an existing review'

    param :path, :id, :integer, :required, "ID"
  end

  def cancel
    begin
      reservation = Reservation.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), reservation: @reservation}
      return
    end

    #TO DO change status based on user or hotel 
    if reservation.update(:status => :hotel_cancelled)
      render json: { meta: meta_response( 200, 'all ok'), reservation: @reservation}
    else
      render json: { meta: meta_response( 500, 'Server error'), reservation: @reservation}
    end

  end

  swagger_api :destroy do
    summary "Deletes an existing reservation"
    param :path, :id, :integer, :optional, "ID"
  end

  def destroy
    begin
      @reservation = Reservation.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), reservation: @reservation}
      return
    end

    if @reservation.destroy
      render json: { meta: meta_response( 200, 'all ok'), reservation: @reservation }
    else
      render json: { meta: meta_response( 500, 'Server error'), reservation: @reservation }
    end
  end

  swagger_api :details do
    summary "Provide all reservation details for a hotel within a date-time range"
    param :form, :hotel_id, :integer, :required, "Hotel ID"
    param :form, :from, :date, :required, "From"
    param :form, :to, :date, :required, "To"
  end
  def details
  	@details = Reservation.details(params)
  	render json: { meta: meta_response( 200, 'all ok'), details: @details }
  end

  private
  def reservation_params
    params.permit(:customer_id, :hotel_id, :from, :to, :comment, :table_id, :no_of_persons);
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>
	
	<% if @reservation.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@reservation.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @reservation.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>
	<% end %>
	<p>
		<%= f.label :hotel_id %><br>
		<%= f.number_field :hotel_id %>
	</p>

	<p>
		<%= f.label :table_id %><br>
		<%= f.number_field :table_id %>
	</p>

	<p>
		<%= f.label :status %><br>
		<%= f.number_field :status %>
	</p>

	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>
	

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>	
<%= render 'form' %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing All Reservations</h1>

<table>
	<tr>
		<th>
			Hotel Id
		</th>
		<th>
			Table Id
		</th>
		<th>
			Customer Id
		</th>
		<th>
			Status
		</th>
		<th>
			Comment
		</th>

		<th colspan="2">
		</th>
	</tr>

	<% @reservations.each do |reservation| %>
		<tr>
			<td><%= reservation.hotel_id %></td>
			<td><%= reservation.table_id %></td>
			<td><%= reservation.customer_id %></td>
			<td><%= reservation.status %></td>
			<td><%= reservation.comment %></td>
			<td><%= link_to 'Show', reservation_path(reservation) %></td>
			<td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
			<td><%= link_to 'Cancel', cancel_reservation_path(reservation) %></td>
			<td><%= link_to 'Destroy', reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'New Reservation', new_review_path %>

app/views/reservations/new.html.erb
<h1> New Reservation </h1>
<%= render 'form' %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
	<strong>Hotel Id:</strong>
	<%= @reservation.hotel_id %>
</p>

<p>
	<strong>Table Id:</strong>
	<%= @reservation.table_id %>
</p>

<p>
	<strong>Customer Id:</strong>
	<%= @reservation.customer_id %>	
</p>

<p>
	<strong>Status:</strong>
	<%= @reservation.status %>	
</p>

<p>
	<strong>Comment:</strong>
	<%= @reservation.comment %>
</p>	
<%= link_to 'Edit', edit_reservation_path(@reservation) %>
<%= link_to 'Back', reservations_path %>