config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

 authenticate :admin_user do
    get '/' => redirect('/doc/index.html?url=/apidocs/api-docs.json')
  end
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: :json }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

    resources :managers do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :hotels do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :customers do
      collection do
        post 'signup'
        post 'login'
        put 'logout'
      end
    end

    resources :reviews do
      
    end
  
    resources :reservations do
      member do
        get 'cancel'
        post 'details'
        post 'approve'
      end
    end

  end
end

end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < Api::V1::ApiController


  swagger_controller :reviews, " Reviews Controller"


  swagger_api :index do
    summary 'Lists all the reviews'
  end

  def index
    @reviews = Review.all
    render json: { meta: meta_response( 200 , 'all ok'), reviews: @reviews }
  end


  swagger_api :show do
    summary 'Show details of a review'

    param :path, :id, :integer, :required, "ID"
  end

  def show
    begin
      @review = Review.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), review: @review}
      return
    end

    render json: { meta: meta_response( 200, 'all ok'), review: @review }
  end


  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end


  swagger_api :create do
    summary 'Create a new review'

    param :form, :title, :string, :required, "Title"
    param :form, :review, :string, :required, "Review"
    param :form, :rating, :integer, :required, "Rating"
    param :form, :hotel_id, :integer, :required, "Hotel ID"
    param :form, :customer_id, :integer, :required, "Customer ID"
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      render json: { meta: meta_response( 200, 'all ok'), review: @review}
    else
      render json: { meta: meta_response( 500, 'Server Error'), review: @review}
    end
  end


  swagger_api :update do
    summary 'Update an existing review'

    param :path, :id, :integer, :required, "ID"
    param :form, :title, :string, :optional, "Title"
    param :form, :review, :string, :optional, "Review"
    param :form, :rating, :integer, :optional, "Rating"
  end

  def update
    begin
      @review = Review.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), review: @review}
      return
    end

    if @review.update(review_params)
      render json: { meta: meta_response( 200, 'all ok'), review: @review}
    else
      render json: { meta: meta_response( 500, 'Server error'), review: @review}
    end
  end


  swagger_api :destroy do
    summary "Deletes an existing review"
    param :path, :id, :integer, :optional, "ID"
  end

  def destroy
    begin
      @review = Review.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render json: { meta: meta_response( 404, 'id doesn\'t exists'), review: @review}
      return
    end
    if @review.destroy
      render json: { meta: meta_response( 200, 'all ok'), review: @review}
    else
      render json: { meta: meta_response( 500, 'Server error'), review: @review}
    end

  end

  private
  def review_params
    params.permit(:title, :review, :rating, :hotel_id, :customer_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
	
	<% if @review.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@review.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @review.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :hotel_id %><br>
		<%= f.number_field :hotel_id %>
	</p>

	<p>
		<%= f.label :review %><br>
		<%= f.text_area :review %>
	</p>

	<p>
		<%= f.label :rating %><br>
		<%= f.number_field :rating %>
	</p>

	<p>
		<%= f.hidden_field :customer_id, :value => 1 %>
	</p>

	<p>
		<%= f.hidden_field :menu_item_id, :value => 1 %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>	
<%= render 'form' %>
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing All Reviews</h1>

<table>
	<tr>
		<th>
			Customer Id
		</th>
		<th>
			Hotel Id
		</th>
		<th>
			Menu Item Id
		</th>
		<th>
			Title
		</th>
		<th>
			Review
		</th>
		<th>
			Rating
		</th>

		<th colspan="2">
		</th>
	</tr>

	<% @reviews.each do |review| %>
		<tr>
			<td><%= review.customer_id %></td>
			<td><%= review.hotel_id %></td>
			<td><%= review.menu_item_id %></td>
			<td><%= review.title %></td>
			<td><%= review.review %></td>
			<td><%= review.rating %></td>
			<td><%= link_to 'Show', review_path(review) %></td>
			<td><%= link_to 'Edit', edit_review_path(review) %></td>
			<td><%= link_to 'Destroy', review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1> New Review </h1>
<%= render 'form' %>
<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @review.title %>
</p>

<p>
	<strong>Customer:</strong>
	<%= @review.customer_id %>
</p>

<p>
	<strong>Hotel:</strong>
	<%= @review.hotel_id %>	
</p>

<p>
	<strong>Menu Item:</strong>
	<%= @review.menu_item_id %>	
</p>

<p>
	<strong>Review:</strong>
	<%= @review.review %>
</p>
<p>
	<strong>Rating:</strong>
	<%= @review.rating %>
</p>	
<%= link_to 'Edit', edit_review_path(@review) %>
<%= link_to 'Back', reviews_path %>